name: Publish

on:
  push:
    tags:
      - "*"
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: ðŸ›Žï¸ Checkout
        uses: actions/checkout@v2

      - name: ðŸ§ª Setup elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: 1.12.0 # Define the elixir version [required]
          otp-version: 24.0 # Define the OTP version [required]

      - name: â¬‡ï¸ Install elixir dependencies
        run: mix deps.get

      - name: ðŸ”¨ Build dependencies
        run: mix deps.compile

      - name: ðŸ”¨ Build project
        run: mix clean && mix compile --warnings-as-errors

      - name: â–¶ï¸ Run tests
        run: mix test

      - name: ðŸš€ Publish package to hex.pm
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: |
          if [[ -z "${HEX_API_KEY}" ]]; then
            echo "HEX_API_KEY is not set" && exit 1
          fi

          echo "===> install hex"
          echo 
          mix local.hex --force
          mix local.rebar --force

          echo "===> install dependencies"
          echo 
          mix do deps.get, deps.compile

          echo "===> Build hex package"
          echo 
          mix hex.build

          echo "===> Publishing hex package"
          echo
          mix hex.publish --yes
